### ISSUE TITLE
User guide not clear:

### ISSUE THREAD

**Issue by martinschorb** [AllenInstitute/render-python#149]
Hi,

I tried to follow the tutorial and found that in (https://github.com/AllenInstitute/render-python/blob/master/docs/guide/index.rst), the command `AffineTransform` is not part of the current `renderapi.transform.Transform` class. I tried `AffineModel` instead and this seems to work so far.

**Comment by martinschorb** [comment]
It looks like also the [example repo](https://github.com/fcollman/render-python-apps) is outdated. I found a bunch more of Python2 `print`  statements than in the python3 branch. 

Also some classes have been renamed.

I forked the repo and will try to get it to work again.

**Comment by RussTorres** [comment]
Hello,

Thanks for pointing this out!  First I'd like to apologize for this friction -- we have not had to personally bring anyone up to speed on this recently and missed out on changing this documentation.
There is actually a much more complete "example" repo using this for EM processing that we should switch to (one that is python 2/3 compatible and has automated testing).  Find that repo here: https://github.com/AllenInstitute/render-modules
I'm pretty sure there is also more up-to-date array tomography code if that is what interests you.  It's likely still using python 2, but render-python methods should be current.  We are not maintaining that code currently, but happy to ask those who've used it recently.

And in terms of the user guide I agree that it should be updated/extended, however it looks like the `AffineTransform`/`AffineModel` thing might just be a typo (or from an ancient version of this), since it doesn't exist anywhere else in the repo.

**Comment by martinschorb** [comment]
Hi, 
Thanks for pointing me to the more recent repo. 
I am trying to set up a generic render-based alignment/registration service at our institute for different types of data (FIB-SEM, ss-TEM, SBSEM,...) and found   your/@fcollman 's client modules the most comprehensible entry point. Right now, I can create initial tilespecs and import them as the first stack into render. I will try to go further based on your new modules.

Cheers

**Comment by martinschorb** [comment]
Hi,

I started to look into the processing routines for creating tile pairs and generating the point matches. However, when I call the client modules, I always get a 
```

  File "<ipython-input-21-85c128264abb>", line 1, in <module>
    module1.run()

  File "<ipython-input-8-c5d10322cbd0>", line 39, in run
    self.output({'tile_pair_file':tilepairJsonFile})

  File ".../envs/render/lib/python3.7/site-packages/argschema/argschema_parser.py", line 229, in output
    output_path = self.args['output_json']

KeyError: 'output_json'
```

I have created the `input_data` based on the example dicts provided with the module. There is no definition of the output JSON.

Do I need to specify another parameter in the main part?
 
```
if __name__ == "__main__":
    module = TilePairClientModule(input_data=example)
    module.run()
```

**Comment by RussTorres** [comment]
Those modules are based around `argschema`, which integrates some argparse-like command line functionality with marshmallow schemas.  The base classes in `argschema` allow for defining "input_json" and "output_json" arguments.  When calling from the command line you can add the "--output_json" argument or add it to your input dictionary.

We use these as steps in an automated processing workflow in which there is always a "--input_json" (file that looks like the example_input) and "--output_json" so that we can keep track of the inputs and outputs of various runs.  This is important for the tilepairclientmodule because it is what gives a path to the generated file.  To skip creating a file that gives you the location of another file you could just use the render-python client module directly (the module code doesn't do much more than wrap this in a command-line friendly script).

More generally, though, it looks like you're doing these interactively, so you could add false command line arguments to the modules like:
```python
module = TilePairClientModule(input_data=example, args=["--output_json", "/tmp/mytempjson"])
module.run()
```
If you're really not interested in having the output saved to a file, you can usually comment out the `self.output` lines without affecting the script too much.

For some of those modules we've tried to  break out useful staticmethods and classmethods where possible to facilitate code reuse, but I suspect there is a lot more that could be done.
